name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: '5.15.2'
  BUILD_TYPE: 'MinSizeRel'

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        target: 'desktop'
        version: '${{env.QT_VERSION}}'
        modules: 'qtcharts'
        archives: 'qtbase'
        tools: 'tools_qtcreator,qt.tools.qtcreator'
        install-deps: 'true'
        setup-python: 'false'

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/logdoctor -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target all

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

