name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: '5.15.2'
  BUILD_TYPE: 'MinSizeRel'

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: '${{matrix.config.os}}'
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest,  arch: gcc_64        }
          - { os: windows-latest, arch: win64_mingw81 }
          - { os: macos-latest,   arch: clang_64      }

    steps:
    - name: Get LogDoctor
      uses: actions/checkout@v3
    
    
    - name: Get CMake
      uses: lukka/get-cmake@latest

    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        target: 'desktop'
        arch: '${{matrix.config.arch}}'
        version: '${{env.QT_VERSION}}'
        modules: 'qtcharts'
        archives: 'icu qtbase qttools qttranslations'
        tools: 'tools_ifw tools_cmake tools_qtcreator,qt.tools.qtcreator tools_qtcreator_gui,qt.tools.qtcreator_gui'
        install-deps: 'true'
        setup-python: 'false'


    - name: Configure CMake
      if: runner.os != 'Windows'
      run: cmake -S ${{github.workspace}}/logdoctor -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure CMake
      if: runner.os == 'Windows'
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      run: cmake -S ${{github.workspace}}\logdoctor -B ${{github.workspace}}\build "-DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}}" "-DCMAKE_GENERATOR:STRING=NMake Makefiles JOM" "-DCMAKE_MAKE_PROGRAM:STRING=jom" "-DCMAKE_CXX_COMPILER:FILEPATH=${{github.workspace}}\Qt\${{env.QT_VERSION}}\mingw81_64\bin\gcc.exe"


    - name: Build
      if: runner.os != 'Windows'
      run: cmake --build ${{github.workspace}}/build --target all

    - name: Build
      if: runner.os == 'Windows'
      run: cmake --build ${{github.workspace}}/build --target ALL_BUILD 

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}

