name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: '5.15.2'
  BUILD_TYPE: 'MinSizeRel'

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: '${{matrix.config.os}}'
    strategy:
      fail-fast: false
      matrix:
        config:
          #- { os: ubuntu-latest,  arch: gcc_64        }
          - { os: windows-latest, arch: win64_mingw81 }
          #- { os: macos-latest,   arch: clang_64      }

    steps:
    - name: Get LogDoctor
      uses: actions/checkout@v3

    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        target: 'desktop'
        arch: '${{matrix.config.arch}}'
        version: '${{env.QT_VERSION}}'
        modules: 'qtcharts'
        archives: 'icu qtbase qttools qttranslations'
        tools: 'tools_ifw tools_cmake tools_qtcreator,qt.tools.qtcreator'
        install-deps: 'true'
        setup-python: 'false'
    
    
    - name: Append PATHs (WIN)
      if: runner.os == 'Windows'
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: PATH
        value: $env:PATH;D:/a/LogDoctor/Qt/Tools/CMake_64/bin;D:/a/LogDoctor/Qt/Tools/QtCreator/bin;D:/a/LogDoctor/Qt/Tools/QtCreator/bin/jom


    - name: Configure CMake (NIX)
      if: runner.os != 'Windows'
      run: cmake -S ${{github.workspace}}/logdoctor -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure CMake (WIN)
      if: runner.os == 'Windows'
      run: |
        ls D:/a/LogDoctor/Qt/Tools/CMake_64r
        ls D:/a/LogDoctor/Qt/Tools/CMake_64r/bin
        ls D:/a/LogDoctor/Qt/Tools/QtCreator
        ls D:/a/LogDoctor/Qt/Tools/QtCreator/bin
        ls D:/a/LogDoctor/Qt/Tools/QtCreator/bin/jom
        cmake -S ${{github.workspace}}\logdoctor -B ${{github.workspace}}\build "-DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}}" "-DCMAKE_GENERATOR:STRING=NMake Makefiles JOM" "-DCMAKE_MAKE_PROGRAM:STRING=jom" "-DCMAKE_CXX_COMPILER=g++.exe" "-DCMAKE_PREFIX_PATH:PATH=D:/a/LogDoctor/Qt/5.15.2/mingw81_64" "-DQT_DIR:PATH=D:/a/LogDoctor/Qt/5.15.2/mingw81_64/lib/cmake/Qt5"


    - name: Build (NIX)
      if: runner.os != 'Windows'
      run: cmake --build ${{github.workspace}}/build --target all

    - name: Build (WIN)
      if: runner.os == 'Windows'
      run: cmake --build ${{github.workspace}}/build --target ALL_BUILD 

    - name: '#!? (WIN)'
      if: runner.os == 'Windows' && failure()
      run: echo "O Windows, Windows, wherefore art thou Windows?"

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}

